GET http://localhost:8080/actuator

###

GET http://localhost:8080/actuator/health

###

GET http://localhost:8080/actuator/info

###
GET http://localhost:8080/actuator/metrics/jvm.memory.used

###

GET http://localhost:8080/log

###

POST http://localhost:8080/actuator/loggers/linkedin.data
Content-Type: application/json

{ "configuredLevel": "ERROR" }
