POST http://localhost:8080/dirty-secrets
Content-Type: application/json

{
  "name": "Freddy",
  "secret": "Killed an elderly couple and did time."
}

###

POST http://localhost:8080/dirty-secrets
Content-Type: application/json

{
  "name": "Doug",
  "secret": "Former Alcoholic."
}

###

GET http://localhost:8080/dirty-secrets

###

DELETE http://localhost:8080/dirty-secrets
Content-Type: application/json

[
  "6c6ad75e-8071-4331-a4b1-6418de99c62f",
  "80390247-3568-4df5-a09b-ef6cc0b8cb44"
]